title: "Portfolio"
description: "PhD researcher in shape memory polymer composite, batteries, and physics-informed machine learning"
url: "https://mehrabhasan.github.io"

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Mehrab Hasan"
  avatar: "/assets/profile.jpg"
  bio: "PhD researcher in shape memory polymer composite, batteries, and physics-informed machine learning."
  location: "Norman, Oklahoma"
  email: "mehrab.hasan3513@gmail.com"
  links:
    - label: "LinkedIn"
      url: "https://linkedin.com/in/mehrab-hasan-974471129"
    - label: "GitHub"
      url: "https://github.com/mehrabhasan.github.io"
